---
title: "Exercise 5"
output: github_document
---

Prepared based on the Wisdom and/or Madness of Crowds game by Nicky Case available at https://ncase.me/crowds/

#### What is complex contagion and how it’s different from simple contagion
Simple contagion refers to spreading processes induced by a single exposure to a contagious entity while complex contagion demands multiple exposures for transmission. The relative percentage of infected immediate network matters that simple contagions are just complex contagions with 0% infection threshold. Simple contagions are catchy ideas that spread quickly to everyone but lack lasting impact on what we think or how we live, like spreading of virus. Complex contagions, however, come with greater hurdles that an entity would be transmitted only if certain percentage of their immediate network entities do so, i.e. infection threshold more than 0%. Tis is a much deeper process of social spreading that we consider whether to adopt to a new belief or behavior. In other words, complex contagions require social affirmation from multiple sources. 

Both types of contagions can be good or bad (or neutral or ambiguous). There's strong statistical evidence that smoking, health, happiness, voting patterns and corporation levels are 'contagious'. And even some evidence that suicides and mass shootings are too. To better illustrate the differences between simple and complex contagions, we can consider the spread of good word of mouth as an example for simple contagion that one acquaintance would believe and tell another how good a product or service is without much hesitation / validation, and avant garde fashions as complex contagion in which peer's recognition and how they wear can easily change our adaptation and co-create new trends. 

#### What does complex contagion mean for diffusion of behaviors in organization?
Within an organization, work culture, values, knowledge and behaviors are all about contagions and connections. Contagions are how people pass on beliefs and behaviors - not only influence their immediate network, but also propagate to their secondary network and beyond. It could be the pressure to conform to company's policy where one employee behaving unusually is random noise while many people behavior unusually demonstrate the strength of information signal. If a transformation or a new behavior is adopted by one of the prominent individuals within an organization, like a department head or a leader of worker's association, the gesture would be spread to many people very quickly. Hence, it is important to seek the buy-in from influential people or ask them to set a role model of some positive behavior before rolling out or promoting to the rest of the community. 

However, the more connected someone is, the harder it is to convince them that a new idea or behavior is legitimate. The more contacts they have, the more adopters it takes to change their mind. This is what we learnt from the game that complex ideas get crushed by groupthink, besides ideas can't spread when there are too few connections. As suggested, the trick is to build a small world network with optimal mix of bonding and bridging. To establish effective behavior diffusion in the real world, an organization can form small groups led by a group leader while limiting his/her exposure to many other group leaders but some within a cluster or just one centralized commander. A good example of effective transformation would be the train the trainers approach widely used in the consulting industry. 

#### How can we use the threshold models to better manage prosocial behavior in organizations, learning, and toxic or unproductive behaviors

Prosocial behaviors, learning and toxi behaviors can all be explained by contagion models with different setup and thresholds and illustrated with real life examples. Prosocial behaviors like employee services, peer support and inclusion & diversity initiatives are usually extended from organization's visions and promoted top-down. With blessings from upper management, some individuals with bigger ambition would volunteer to take up the role as the person in charge and mobilize a core team by recruiting a few people sharing similar interest or values. Now that we've learnt about the threshold contagion models, we can facilitate the difussion of prosocial behaviors by recruiting advocates from various teams for better penetration across departments and levels of the organizations. Having communications and reinforcement by the reputatable 'source' would also be beneficial - when an employee received the letter from CEO promoting a service week and be invited personally by the CRS advocate from his team, more likely he/she will join the event.  

The similar applies in learning and likely with much lower 'infection' threshold, as knowledge is facts that can easily be digested without much peer's affirmation needed. An example here would be the train-the-trainers approach for employees to learn a new operational system before its launch. Often the leader or the coordinator of a team (who know most people having highest degree centrality) is nominated to attend such training and share their knowledge among his/her network afterwards. Trainers would feel greater responsibility being the elites and learn more proactively, while other learners are more motivated having a close trainer. This is particularly useful in large organization to carry out training in large scale. On the contrary, if the organization trains its employees in a big class of size like 100+, we can anticipate more complains (might be resulted from groupthink) and a lack of attentiveness than the actual learning outcomes. 

Toxic or unproductive behaviors are to be identified and paused from being transmitted to one's immediate network. It is simulated in the wisdom and madness game that to break the connection between nodes to prevent the contagion from spreading to everyone. In organizations like schools, bad students might be penalized with separate detention classes or be relocated to seats which are surronded by good students, in the attempt to separate out from students who are vulunerable to temptations/imitations and induced them with good behaviors instead. We are also aware that the more connections can hurt the spread of commplex ideas as suggested by the groupthink concept. If the toxic behaviors have been well established and people are resistance to good behaviors that challenge their belifs or egos, it might be a good idea for class teacher to break the class in small groups and have more direct coaching and conseilling with each group - its leader and each of the members, yet more effort-intensive. Hence, it is recommended to cultivate good behaviors before it is too late that the bad ones become the norm. 

Submitted by Chelsea Hon.



