---
title: "Exercise 1"
output: github_document
---

## 1. Get contact data
Get a copy of connections data https://www.linkedin.com/psettings/member-data

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## 2. Load Data

```{r}
connections <- read.csv("Connections_fixed.csv")
view(connections)
```

## 3. Get count of contacts by employer

```{r}
library(dplyr)
connections %>% count(Company) %>% arrange(-n) %>% head(20)
#connections %>% group_by(Company) %>% summarise(count_contacts = n()) %>%  arrange(desc(count_contacts)) 
```

## 4. Create nodes and edges dataframes to use with igraph

```{r}
library(tidygraph)
library(ggraph)

# Create labels
connections$initial = substr(connections$Last.Name, 1,1)
connections = connections %>% 
  mutate(name = paste(First.Name, initial, sep = " "))

# Create nodes
nodes <- connections %>% 
  select(c("name", "Company")) %>% 
  rowid_to_column("id")

# Create edges
edges <- connections %>% select(c(name, Company)) %>% 
  left_join(nodes %>% select(c(id,name)), by = c("name"="name"))

edges <- edges %>% left_join(edges, by = "Company", keep=FALSE) %>% 
  select(c("id.x", "id.y", "Company")) %>% 
  filter(id.x!=id.y)

colnames(edges) <- c("x", "y", "Company")

view(edges)
```

## 5. Plot the resulting network
```{r}
network <- tbl_graph(nodes=nodes, edges=edges, directed=FALSE)

ggraph(network, layout = "graphopt") + 
  geom_edge_link(aes(color=Company), show.legend=FALSE) + 
  geom_node_point()+
  theme_graph()
```

